
default_platform(:ios)

platform :ios do
  desc "version up"
  lane :prepare_release do |options|

   version = increment_version_number(
      bump_type: options[:bump_type],
      xcodeproj: "PostLike.xcodeproj"
   )
   release_branch = "release/#{version}"
   sh "git checkout -b #{release_branch}" 
   git_commit(path: ".", message: "Bump to #{version}")
   push_to_git_remote
   create_pull_request(
     api_token: ENV['GITHUB_TOKEN'],
     repo: "taichi830/PostLike",
     title: "#{version}",
     head: release_branch,
     base: "main",
     body: "Merge release branch #{version} to main"
   )
   create_pull_request(
     api_token: ENV['GITHUB_TOKEN'],
     repo: "taichi830/PostLike",
     title: "#{version}",
     head: release_branch,
     base: "develop",
     body: "Merge release branch #{version} to develop"
   )
  end




  desc "release to appstore"
  lane :release_to_appstore do
     bump_build_version_with_commit
     build_to_release
  end
 

 # Private

 private_lane :build_to_release do
  create_keychain_for_CI if is_ci
  api_key = app_store_connect_api_key(
    key_id: ENV['ASC_KEY_ID'],
    issuer_id: ENV['ASC_ISSUER_ID'],
    key_content: ENV['ASC_KEY_CONTENT']
  )
  match(
    api_key: api_key,
    type: "appstore",
    readonly: is_ci,
    keychain_name: "postlike_keychain",
    keychain_password: ENV["MATCH_PASSWORD"],
  ) 
  disable_automatic_code_signing(
    use_automatic_signing: false,
    targets: ["PostLike"],
    code_sign_identity: "iPhone Distribution",
    team_id: ENV["TEAM_ID"],
    profile_name: "match AppStore com.postlike.PostLike"
  )
  gym(
    workspace: "PostLike.xcworkspace",
    configuration: "Release",
    scheme: "PostLike_release",
    export_method: "app-store",
  )
  deliver(
     api_key: api_key,
     submit_for_review: false,
     force: true,
     skip_screenshots: true,
     skip_metadata: true,
     precheck_include_in_app_purchases: false
   )
 end

 private_lane :bump_build_version_with_commit do
   increment_build_number(
     xcodeproj: "PostLike.xcodeproj"
   )
   git_commit(path: ".", message: "Version Bump")
 end


 private_lane :create_keychain_for_CI do
   create_keychain(
     name: "postlike_keychain",
     password: ENV["MATCH_PASSWORD"],
     default_keychain: true,
     unlock: true,
     timeout: 3600,
     lock_when_sleeps: false
   )
 end

 





end

















