
name: Auto merge release Pull Request

on:
  pull_request:
    types: [labeled]

jobs:
  auto-merge:
    if: github.event.label.name == 'release'
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        name: Checkout repository
      - name: Extract branch name
        uses: mdecoleman/pr-branch-name@1.0.0
        id: extract_branch
        with:
          repo-token: ${{ secrets.PERSONAL_API_TOKEN }}
      - uses: yanamura/git-flow-merge-action@v1
        name: git-flow-merge
        with: 
          github_token: ${{ secrets.PERSONAL_API_TOKEN }}
          branch: ${{ steps.extract_branch.outputs.branch }}
          develop_branch: "develop"
          main_branch: "main"
