
name: Create tag & release

# Controls when the workflow will run
on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  tag_release: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Extract version
        run: |
             echo '${{ github.event.pull_request.head.ref }}' | sed 's/release\///'
             VERSION=$(echo ${{ github.event.pull_request.head.ref }} | sed "s/release\///")
             echo ::set-output name=version::$VERSION
        id: extract_version
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_API_TOKEN }}
        with:
          tag_name: ${{ steps.extract_version.outputs.version }}
          release_name: v${{ steps.extract_version.outputs.version }}
          draft: false
          prerelease: false
  
  submit:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup SSH Keys and known_hosts for fastlane match
      run: |
        # .ssh ディレクトリの作成
        mkdir -p ~/.ssh

        # .ssh/known_hosts への github.com の登録
        ssh-keyscan -H github.com >> ~/.ssh/known_hosts

        # .ssh/config の作成
        cp -f ./config ~/.ssh/config

        # .ssh/id_rsa の作成
        echo ${SSH_KEY} > ~/.ssh/id_rsa
        sed -i -e "s#\\\\n#\n#g" ~/.ssh/id_rsa

        ＃ .ssh/id_rsa のアクセス制限
        chmod 600 ~/.ssh/id_rsa
      env:
        # 3: 秘匿情報の受け渡し
        PRIVATE_KEY: ${{ secrets.GITHUB_ACTIONS_SSH_PRIVATE_KEY }}
    - name: release app
      run: |
        bundle install
        bundle exec fastlane release_to_appstore
      env:
        TEAM_ID: ${{ secrets.TEAM_ID }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

  
  
  
  
  
  
  
  
          
          
          
