
name: Create tag & release

# Controls when the workflow will run
on:
  push:
    branches: [main]

jobs:
  tag_release: 
    runs-on: [macOS]
    steps:
      - uses: actions/checkout@v2
      - name: Extract version
        run: echo "##[set-output name=version;]$(/usr/libexec/PulishBuddy -c 'print":CFBundleShortVersionString"' path/Info.plist)"
        id: extract_version
      - name: Create Release
        uses: actions/create_release@v1
        with:
          tag_name: ${{ step.extract_version.outputs.version }}
          release_name: v${{ step.extract_version.outputs.version }}
          default: false
          prerelease: false
  
  submit:
    runs-on: [macOS]
    steps:
    - uses: actions/checkout@v2
    - name: release app
      run: |
        bundle install
        bundle exec fastlane release_to_appstore
      env:
        TEAM_ID: ${{ secrets.TEAM_ID }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

  
  
  
  
  
  
  
  
          
          
          
