
name: PrePare release

on:
  workflow_dispatch:
    inputs:
     bump_type:
      description: 'Bump Type(major or minor)'
      required: true
      default: 'minor'

jobs:
  prepare_release:
  
    runs-on: macos-latest

    steps:
      
      - uses: actions/checkout@v2
        with:
          ref: develop

      - name: Increment and commit version
        env: 
          XCODE_VERSION: '12.5'
        run: |
          xcode select $XCODE_VERSION
          bundle install
          bundle exec fastlane prepare_release
          bump_type: ${{ github.event.inputs.bump_type }}
          
