name: PrePare release

on:
  workflow_dispatch:
    inputs:
     bump_type:
      description: 'Bump Type(major or minor)'
      required: true
      default: 'minor'

jobs:
  prepare_release:
  
    runs-on: macos-latest
    env:  
      GITHUB_TOKEN: ${{ secrets.PERSONAL_API_TOKEN }}
      
    steps:
      
      - uses: actions/checkout@v2
        with:
          ref: develop

      - name: Increment and commit version
      
        run: |
          bundle install
          bundle exec fastlane prepare_release bump_type: ${{ github.event.inputs.bump_type }}

          
          
          
          
